---
# tasks file for testlink

- name: Enter "Check process" stage
  debug:
  msg: '==> Check process ...'

# Nginx
- name: Check nginx process
  shell: ps -A | grep nginx
  register: nginx_process
  changed_when: false
  tags: debug

- name: Print nginx process
  debug:
    msg: "{{ nginx_process.stdout_lines }}"
  tags: debug

# PHP
- name: Check php process
  shell: ps -A | grep php-fpm
  register: php_process
  changed_when: false
  tags: debug

- name: Print php process
  debug:
    msg: "{{ php_process.stdout_lines }}"
  tags: debug

# MySQL
- name: Check MySQL server process
  shell: ps -A | grep mysql
  register: mysql_process
  changed_when: false
  tags: debug

- name: Print Mysql process
  debug:
    msg: "{{ mysql_process.stdout_lines }}"
  tags: debug

- name: Enter "Smoke Test" stage
  debug:
  msg: '==> Smoke test ...'

- name: install some packages for test
  become: true
  apt:
    name: curl
    state: present
  tags: test

- name: test the TestLink web app
  shell: "curl -s http://localhost/login.php | grep title"
  register: curl_testlink_web
  changed_when: false
  tags:
    - test
    - skip_ansible_lint

- name: print curl result
  debug:
    msg: "{{ curl_testlink_web.stdout_lines }}"
  tags: test

# vim: ft=ansible :
